[project]
name = "iicpc-dev-interns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "psutil>=7.1.3",
    "pynput>=1.8.1",
    "scapy>=2.6.1",
]
